export const countryPhoneCodes = [
    { country: "United States", code: "+1" },
    { country: "United Kingdom", code: "+44" },
    { country: "Australia", code: "+61" },
    { country: "India", code: "+91" },
    { country: "China", code: "+86" },
    { country: "Germany", code: "+49" },
    { country: "France", code: "+33" },
    { country: "Italy", code: "+39" },
    { country: "Spain", code: "+34" },
    { country: "Mexico", code: "+52" },
    { country: "Brazil", code: "+55" },
    { country: "Russia", code: "+7" },
    { country: "Japan", code: "+81" },
    { country: "South Korea", code: "+82" },
    { country: "Singapore", code: "+65" },
    { country: "Malaysia", code: "+60" },
    { country: "Thailand", code: "+66" },
    { country: "Vietnam", code: "+84" },
    { country: "Indonesia", code: "+62" },
    { country: "Philippines", code: "+63" },
    { country: "South Africa", code: "+27" },
    { country: "Egypt", code: "+20" },
    { country: "Nigeria", code: "+234" },
    { country: "Argentina", code: "+54" },
    { country: "Colombia", code: "+57" },
    { country: "Turkey", code: "+90" },
    { country: "Saudi Arabia", code: "+966" },
    { country: "United Arab Emirates", code: "+971" },
    { country: "Israel", code: "+972" },
    { country: "Pakistan", code: "+92" },
    { country: "Bangladesh", code: "+880" },
    { country: "Sri Lanka", code: "+94" },
    { country: "Nepal", code: "+977" },
    { country: "New Zealand", code: "+64" },
    { country: "Sweden", code: "+46" },
    { country: "Norway", code: "+47" },
    { country: "Denmark", code: "+45" },
    { country: "Finland", code: "+358" },
    { country: "Iceland", code: "+354" },
    { country: "Switzerland", code: "+41" },
    { country: "Austria", code: "+43" },
    { country: "Netherlands", code: "+31" },
    { country: "Belgium", code: "+32" },
    { country: "Portugal", code: "+351" },
    { country: "Poland", code: "+48" },
    { country: "Czech Republic", code: "+420" },
    { country: "Hungary", code: "+36" },
    { country: "Greece", code: "+30" },
    { country: "Ireland", code: "+353" },
    { country: "Romania", code: "+40" },
    { country: "Ukraine", code: "+380" },
    { country: "Belarus", code: "+375" },
    { country: "Kazakhstan", code: "+7" },
    { country: "Chile", code: "+56" },
    { country: "Peru", code: "+51" },
    { country: "Venezuela", code: "+58" },
    { country: "Cuba", code: "+53" },
    { country: "Jamaica", code: "+1-876" },
    { country: "Trinidad and Tobago", code: "+1-868" },
    { country: "Barbados", code: "+1-246" },
    { country: "Bermuda", code: "+1-441" },
];

